### ISSUE TITLE
UnicodeDecodeError on Windows

### ISSUE THREAD

**Issue by me-12** [openimages/dataset#29]
When trying to run "classify.py" on the Windows CMD I get the following error:

```
Traceback (most recent call last):
  File "D:\Softwareprojects\tensorflow\dataset-master\tools\classify.py", line 166, in <module>
    tf.app.run()
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:\Softwareprojects\tensorflow\dataset-master\tools\classify.py", line 133, in main
    img_data = tf.gfile.FastGFile(image_path).read()
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 122, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 90, in _prepare_value
    return compat.as_str_any(val)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\util\compat.py", line 106, in as_str_any
    return as_str(value)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\util\compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
The problem is triggered by "tf.gfile.FastGFile" which tries to load the image as utf-8 string. https://github.com/openimages/dataset/blob/master/tools/classify.py#L132

 I passed "rb" as option which seems to fix the problem:
`img_data = tf.gfile.FastGFile(image_path, "rb").read()`

**Comment by krasin** [comment]
@me-12 Hi Michael,

that looks correct to me. Would you like to create a pull request with the proposed change?

**Comment by me-12** [comment]
@krasin: done. see #30

**Comment by krasin** [comment]
Thank you, Michael!
