### ISSUE TITLE
OIDv4 Tool Kit Windows 10 Python 3.7

### ISSUE THREAD

**Issue by ManuelSR** [openimages/dataset#90]
Hello,

I have a problem with the toolKit:
OS Windows 10
Python 3.7

[INFO] | Downloading Orange.
Traceback (most recent call last):
File "..\TestToolKit\OIDv4_ToolKit\modules\downloader.py", line 25, in download
columns, rows = os.get_terminal_size(0)
OSError: [WinError 6] Controlador no v▒lido

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "main.py", line 37, in
bounding_boxes_images(args, DEFAULT_OID_DIR)
File "..\OIDv4_ToolKit\modules\bounding_boxes.py", line 62, in bounding_boxes_images
download(args, df_val, folder[0], dataset_dir, class_name, class_code)
File "..\OIDv4_ToolKit\modules\downloader.py", line 27, in download
columns, rows = os.get_terminal_size(1)
OSError: [WinError 6] Controlador no v▒lido

**Comment by ManuelSR** [comment]
The problem was executing with git bash and not with cmd

**Comment by MaisaDaoud** [comment]
MauelSR answer is right, thanks!
